### PR TITLE
Compute

### PR DESCRIPTION
**Pull request by sergicastro**
Added deploy-kvm in mothership plugin

### CODE REVIEW

**Comment by nacx** [comment]
Cool!
It would be nice to include too a property in the config file to set the nfs share (one single property with address:path).

**Comment by sergicastro** [comment]
Yeah!
I think this is the next step to make more configurable this plugin. I will update it soon!

**Comment by sergicastro** [comment]
Done.

As you can see I used two config variables for nfs path and origin, I think it's easier to understand and don't limit the chars from the paths.

**Comment by nacx** [comment]
Shouldn't use the _nfsto_ variable in the abiquo-aim.ini too?

**Pull request merged**
